### ISSUE TITLE
[BUG] Item not found, due to network connectivity issues or poor connection

### ISSUE THREAD

**Issue by samtrek** [Vito0912/abs_flutter#114]
**Bug Report**

**Description of the Issue**
Items not found during network connectivity issues, not the fault of the app, but low and unstable networks results in items not found when items are selected from the library, or personalized library.

**Steps to Reproduce**
Outline the steps needed to reproduce this issue:
1. Open the app when the wifi or their is internet connection.
2. Deliberately disconnect network connectivity
3. Select an item, no item found will be shown.
4. Go back to the library
5. Turn on network connectivity (wifi, or mobile data)
6. Select previous item to listen to
7. Despite connection to the server, the previous item will always return item not found
8. Select another item, this will display as normal

**Expected Behavior**
When poor connectivity occurs, when an item is selected the item should auto refresh if an error occurred before, or an option to refresh the item like the ability to refresh library could be created 

**Observed Behavior**
The item did not load, until the app is killed and then restarted again, and if their is network connectivity it will then load

**Device and Platform Details**
- **Device Type**: Smartphone
- **Operating System**: Android 12
- **App Version**: 1.71.
- **Additional Plugins/Extensions** (if applicable): none

**Comment by Vito0912** [comment]
Will be fixed in next release

**Comment by samtrek** [comment]
ok thank you for the great work, maybe this would also fix the ability to play downloaded podcast or books when the app is offline, or should I open a bug or improvement report?

**Comment by Vito0912** [comment]
Maybe this is releated to #82. Can you open the book (so just where you could play it) when you are offline and restarted the app?
If not please open a bug report and I will look into it. Thank you for testing!

**Comment by samtrek** [comment]
no not related I will have to open a new bug report for it.
