### ISSUE TITLE
BUG: Series with single item causes a render error

### ISSUE THREAD

**Issue by keaganhilliard** [Vito0912/abs_flutter#36]
![image](https://github.com/user-attachments/assets/7aa3ce91-ddb2-4c2d-96e2-d08e1d075d05)

Could be fixed by a `length == 1` edge case like this:
```dart
  List<Widget> _buildItems(double width) {
    List<Widget> items = [];
    if (series.books.length == 1) {
      items.add(
        Padding(
            padding: EdgeInsets.only(
              left: width / 2,
            ),
            child: AlbumImage(series.books[0].id, size: width)),
      );
    } else {
      for (var i = 0; i < min(series.books.length, 6); i++) {
        items.add(
          Padding(
              padding: EdgeInsets.only(
                  left: ((width) / (min(series.books.length, 6) - 1)) * i),
              child: AlbumImage(series.books[i].id, size: width)),
        );
      }
    }
    return items.reversed.toList();
  }
}
```
Which makes it look like this:
![image](https://github.com/user-attachments/assets/bd56ed1e-7e12-477e-b20d-c90501dd7a9b)

**Comment by Vito0912** [comment]
Thanks for pointing that out—I missed it because I had disabled the single series. 

I've made some adjustments to the design. Could you take a look and let me know if everything seems okay?

![image](https://github.com/user-attachments/assets/a8bd29b4-af13-4647-bc0c-6fa30f9bd4c1)

**Comment by keaganhilliard** [comment]
Looks good to me
