### ISSUE TITLE
Chapter Selection View ’Close‘ Button Bug

### ISSUE THREAD

**Issue by GrayGuardian** [Vito0912/abs_flutter#50]
![image](https://github.com/user-attachments/assets/04c3b2cd-fa54-4e28-90db-d05b25d546dc)

Clicking the 'Close' button is expected to close the chapter selection view, but in fact, the entire UI goes back.

**Comment by Vito0912** [comment]
Closed with #52

**Comment by GrayGuardian** [comment]
I tested it with the latest version, and this issue has been fixed. Thank you for your help!
