### ISSUE TITLE
Few improvements 

### ISSUE THREAD

**Issue by ExXxtr3me** [Vito0912/abs_flutter#57]
Hey, your app looks really promising, finally a third party app for Audiobookshelf on Android. 👍

I've got a few suggestions you maybe could add. 

- Select the folder where the Audiobooks are downloaded

- Add bookmarks 

- The small Player on the bottom should disappear when the full screen player is open. ![Screenshot_20241031-102851.png](https://github.com/user-attachments/assets/a22ef860-67f3-4c37-bfe7-4406e848e25e)

**Comment by Vito0912** [comment]
Thanks for the suggestion.
Could you please create independent issues so I can work on them independently as some features require more time than others.

**Comment by ExXxtr3me** [comment]
Sure, will do this.
