### ISSUE TITLE
Series Tab

### ISSUE THREAD

**Issue by ZensiertG** [Vito0912/abs_flutter#63]
The Series Tab (Or filtering by Series in Library Tab) defaults to last entry of a Series to First entry. Other way around would make more sense as default i think.
It shows #&#x2060;4 #&#x2060;3 #&#x2060;2 #&#x2060;1 and i would expect #&#x2060;1 #&#x2060;2 #&#x2060;3 #&#x2060;4

**Comment by Vito0912** [comment]
I intentionally set it up this way, thinking it would be helpful to display the latest items in a series at the top. 
I'll add a setting to allow customization, and I'll set the default to your preference as it is the standard in many apps.

**Comment by ZensiertG** [comment]
Thank you :) yeah i thought it might be intentional, and if you add the new books as you progress that probably works great. So a preference Setting sounds great.
